---
name: Test Suite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: "scripts/install"
        shell: bash
      - name: "Run linting checks"
        run: "scripts/check"
        shell: bash
        if: "${{ matrix.os == 'ubuntu-latest'}}"
      - name: "Build package & docs"
        run: "scripts/build"
        shell: bash
      - name: "Run tests"
        run: "scripts/test"
        shell: bash
      - name: "Enforce coverage"
        run: "scripts/coverage"
        shell: bash
