site_name: Uvicorn
site_description: The lightning-fast ASGI server.

theme:
    name: 'material'

repo_name: encode/uvicorn
repo_url: https://github.com/encode/uvicorn
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Settings: 'settings.md'
    - Deployment: 'deployment.md'
    - Server Behavior: 'server-behavior.md'

markdown_extensions:
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
