site_name: Uvicorn
site_description: The lightning-fast ASGI server.
site_url: https://www.uvicorn.org

theme:
  name: material
  custom_dir: docs/overrides
  logo: uvicorn.png
  favicon: uvicorn.png
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  features:
    - content.code.copy # https://squidfunk.github.io/mkdocs-material/upgrade/?h=content+copy#contentcodecopy
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.footer # https://squidfunk.github.io/mkdocs-material/upgrade/?h=content+copy#navigationfooter
    - toc.follow # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following

repo_name: encode/uvicorn
repo_url: https://github.com/encode/uvicorn
edit_uri: edit/master/docs/

nav:
  - Introduction: index.md
  - Settings: settings.md
  - Deployment: deployment.md
  - Server Behavior: server-behavior.md
  - Release Notes: release-notes.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

hooks:
  - docs/plugins/main.py
