language: python

cache: pip

python:
    - "3.6"
    - "3.7-dev"

env:
    - STARLETTE_TEST_DATABASES="postgresql://localhost/starlette, mysql://localhost/starlette"

services:
    - postgresql
    - mysql

install:
    - pip install -U -r requirements.txt

before_script:
    - psql -c 'create database starlette;' -U postgres

script:
    - scripts/test

after_script:
    - codecov
