language: python

cache: pip

python:
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install codecov
    - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then pip install black; fi

script:
    - scripts/test
    - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then scripts/lint; fi

after_script:
    - codecov
