language: python

cache: pip

python:
    - "3.6"
    - "3.7-dev"

install:
    - pip install -r requirements.txt

script:
    - scripts/test
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then scripts/lint; fi

after_script:
    - codecov
