name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-plugins: "poetry-dynamic-versioning"

    - name: Build the package
      run: |
        poetry build --output $(pwd)/dist --directory $(pwd)/.
        poetry build --output $(pwd)/dist --directory $(pwd)/src/jik-app
        poetry build --output $(pwd)/dist --directory $(pwd)/src/jik-server

    - name: Publish the GitHub artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jik
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download the GitHub artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  pypi-test-publish:
    name: Upload release to Test PyPI
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/jik
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download the GitHub artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish package distributions to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
