name: Sync Repositories

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: encode/uvicorn
            package: uvicorn
            branch: master
          - repository: encode/starlette
            package: starlette
            branch: master

    steps:
      - name: Checkout jik repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Git Filter-Repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          curl -LJO https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          sudo mv git-filter-repo /usr/local/bin/git-filter-repo
          sudo chmod +x /usr/local/bin/git-filter-repo

      - name: Clone ${{ matrix.package }} repository
        run: git clone https://github.com/${{ matrix.repository }}.git

      - name: Filter ${{ matrix.package }} to src/${{ matrix.package }} directory
        run: |
          cd ${{ matrix.package }}
          git filter-repo --to-subdirectory-filter src/${{ matrix.package }}
          cd ..

      - name: Add ${{ matrix.package }} as a remote to jik
        run: git remote add ${{ matrix.package }} ./${{ matrix.package }}

      - name: Fetch ${{ matrix.package }}
        run: |
          git fetch ${{ matrix.package }}
          rm -rf ${{ matrix.package }}

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Attempt to merge ${{ matrix.package }} changes
        id: merge
        run: |
          output=$(git merge -X theirs ${{ matrix.package }}/${{ matrix.branch }} --allow-unrelated-histories 2>&1)

          if [[ $output == *"Already up to date."* ]]; then
            echo "up-to-date=true" >> $GITHUB_OUTPUT
          else
            echo "up-to-date=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: steps.merge.outputs.up-to-date == false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated merge from ${{ matrix.package }}
          delete-branch: true
          branch-suffix: random
          title: Sync ${{ matrix.package }} changes
          body: |
            This PR contains updates from the `${{ matrix.package }}` repository.
            Please review and merge.
          labels: 'auto-sync, needs-review'
